# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "contrail-gremlin-dump-${version}";
  version = "2018-01-19";
  rev = "7eb9424cec6b4ff239d4a1fe667debc2db41ed1d";

  goPackagePath = "github.com/eonpatapon/contrail-gremlin";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/eonpatapon/contrail-gremlin.git";
    sha256 = "1vqldfwjzsqk31884cpzd5fqlyjymiazb728si8x6q7ibr7g8mlp";
  };

  subPackages = [ "gremlin-dump" ];

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
