# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/Jeffail/gabs";
    fetch = {
      type = "git";
      url = "https://github.com/Jeffail/gabs";
      rev = "44ad915e1baa36caddb7db85303c3406042f7187";
      sha256 = "00p1nm2n357amjqy0iwdpm63rqxx035nn47aadkbl2vv5m4k3rm2";
    };
  }
  {
    goPackagePath = "github.com/gocql/gocql";
    fetch = {
      type = "git";
      url = "https://github.com/gocql/gocql";
      rev = "843f6b1d2288839f5d00f92be11cbbebd600ba51";
      sha256 = "1mcm4yc0lhnnyxy641fbdcwfdxvpk64d88sy48jahbsrnqjy1wdc";
    };
  }
  {
    goPackagePath = "github.com/golang/snappy";
    fetch = {
      type = "git";
      url = "https://github.com/golang/snappy";
      rev = "553a641470496b2327abcac10b36396bd98e45c9";
      sha256 = "0kssxnih1l722hx9219c7javganjqkqhvl3i0hp0hif6xm6chvqk";
    };
  }
  {
    goPackagePath = "github.com/hailocab/go-hostpool";
    fetch = {
      type = "git";
      url = "https://github.com/hailocab/go-hostpool";
      rev = "e80d13ce29ede4452c43dea11e79b9bc8a15b478";
      sha256 = "05ld4wp3illkbgl043yf8jq9y1ld0zzvrcg8jdij129j50xgfxny";
    };
  }
  {
    goPackagePath = "github.com/jawher/mow.cli";
    fetch = {
      type = "git";
      url = "https://github.com/jawher/mow.cli";
      rev = "89bd73e5017374498afb615659500c3559ff42b3";
      sha256 = "05c71bsigyrvwccn334n5gx42rk299k0x3psixc691zigbj1zg7f";
    };
  }
  {
    goPackagePath = "github.com/kr/pretty";
    fetch = {
      type = "git";
      url = "https://github.com/kr/pretty";
      rev = "cfb55aafdaf3ec08f0db22699ab822c50091b1c4";
      sha256 = "0441yi9ah9892hxdslv2h35bkfr75g7ajma0q45lqks84pawrdkg";
    };
  }
  {
    goPackagePath = "github.com/kr/text";
    fetch = {
      type = "git";
      url = "https://github.com/kr/text";
      rev = "7cafcd837844e784b526369c9bce262804aebc60";
      sha256 = "0br693pf6vdr1sfvzdz6zxq7hjpdgci0il4wj0v636r8lyy21vsx";
    };
  }
  {
    goPackagePath = "github.com/maraino/go-mock";
    fetch = {
      type = "git";
      url = "https://github.com/maraino/go-mock";
      rev = "c0658195ada54274d527cb1b09ff1d31765509d6";
      sha256 = "1c11cxaqmbwrf106l8647l5jpijqc6w9y11q1839dw0sczp7hrmc";
    };
  }
  {
    goPackagePath = "github.com/op/go-logging";
    fetch = {
      type = "git";
      url = "https://github.com/op/go-logging";
      rev = "970db520ece77730c7e4724c61121037378659d9";
      sha256 = "1cpna2x5l071z1vrnk7zipdkka8dzwsjyx7m79xk0lr08rip0kcj";
    };
  }
  {
    goPackagePath = "github.com/willfaught/gockle";
    fetch = {
      type = "git";
      url = "https://github.com/willfaught/gockle";
      rev = "4f254e1e0f0a12485963192ff605f61f1933e71f";
      sha256 = "0bv3h103ar0bsadrkp1g7cwj3jdsj76jmqhcki4lqcy3f72hpgr3";
    };
  }
  {
    goPackagePath = "gopkg.in/inf.v0";
    fetch = {
      type = "git";
      url = "https://gopkg.in/inf.v0";
      rev = "3887ee99ecf07df5b447e9b00d9c0b2adaa9f3e4";
      sha256 = "0rf3vwyb8aqnac9x9d6ax7z5526c45a16yjm2pvkijr6qgqz8b82";
    };
  }
]
