# DO NOT EDIT
# This file has been generated by
# $ /home/eon/vcs/nixpkgs-contrail/tools/sources.sh /home/eon/vcs/nixpkgs-contrail/tools/sources-R5.0.lst

{pkgs}:
{
  # Head of branch R5.0 of repository github.com/Juniper/contrail-build at 2019-03-29 10:24:19
  build = pkgs.fetchFromGitHub {
    name = "build";
    owner = "Juniper";
    repo = "contrail-build";
    rev = "ae7a389b70b18ffdc29c559c0b23f6a9e1c3f8f3";
    sha256 = "0gv6zi630vw3s56ix0n99v6i4ag1r9djcs6g3rkaxfnl3s46mh6k";
  };
  # Head of branch R5.0 of repository github.com/Juniper/contrail-controller at 2019-03-29 10:24:20
  controller = pkgs.fetchFromGitHub {
    name = "controller";
    owner = "Juniper";
    repo = "contrail-controller";
    rev = "a349d46aabfd3ef39f9171166705f3130d404c22";
    sha256 = "051hpbp8a3dsx7q146k4qb6dnx4npz5871625mzd8252ww360wp1";
  };
  # Head of branch R5.0 of repository github.com/Juniper/contrail-neutron-plugin at 2019-03-29 10:24:28
  neutronPlugin = pkgs.fetchFromGitHub {
    name = "neutronPlugin";
    owner = "Juniper";
    repo = "contrail-neutron-plugin";
    rev = "7a6086975df0ded5b315c4ed89d010c4ec49b528";
    sha256 = "1pc2xmvifgfdjy1q52rj1p67yvszx52jaigb5r019y0llsmi0ghm";
  };
  # Head of branch R5.0 of repository github.com/Juniper/contrail-sandesh at 2019-03-29 10:24:30
  sandesh = pkgs.fetchFromGitHub {
    name = "sandesh";
    owner = "Juniper";
    repo = "contrail-sandesh";
    rev = "cd779c577b814882ae688a5a9c0854cfaa851f27";
    sha256 = "0qwd6ad1xb0rysz03jxzvrakkzs4lpkk7qljp1wykh3i3w4vk811";
  };
  # Head of branch R5.0 of repository github.com/Juniper/contrail-third-party at 2019-03-29 10:24:32
  thirdParty = pkgs.fetchFromGitHub {
    name = "thirdParty";
    owner = "Juniper";
    repo = "contrail-third-party";
    rev = "92489e37bb67d48fe8eaa07b1d689672e144e0db";
    sha256 = "0z8bx1hbxflzx65c8lvgvn0kjyr9h9fqfbzc7abnyfvygc5kp5mh";
  };
  # Head of branch R5.0 of repository github.com/Juniper/contrail-vrouter at 2019-03-29 10:24:33
  vrouter = pkgs.fetchFromGitHub {
    name = "vrouter";
    owner = "Juniper";
    repo = "contrail-vrouter";
    rev = "b02c0ac574e2602046b42e2e2036ad4519f76ac6";
    sha256 = "1cizkgdfd047x37mhkq75cmh58jqcsy8hj2yq3m03v6w111l0ckf";
  };
  # Head of branch R5.0 of repository github.com/Juniper/contrail-common at 2019-03-29 10:24:46
  common = pkgs.fetchFromGitHub {
    name = "common";
    owner = "Juniper";
    repo = "contrail-common";
    rev = "a9e70ecec0bda81ee16b4bd156a3d091620a329f";
    sha256 = "0rm52y7x4bynzhv43qa194ggimz5ggdw30fdxs2w84fvvi6yv4bz";
  };
  # Head of branch R5.0 of repository github.com/Juniper/contrail-analytics at 2019-03-29 10:24:47
  analytics = pkgs.fetchFromGitHub {
    name = "analytics";
    owner = "Juniper";
    repo = "contrail-analytics";
    rev = "574ee3fd9232fcbe5c08cf3d998ac8d76ad0026a";
    sha256 = "1hrz8dvxkrlmd0hl4qd9v7799mxqj9m6jgag7xchy90zx4wmrzms";
  };
  # Head of branch R5.0 of repository github.com/Juniper/contrail-api-client at 2019-03-29 10:25:07
  apiClient = pkgs.fetchFromGitHub {
    name = "apiClient";
    owner = "Juniper";
    repo = "contrail-api-client";
    rev = "a0ed6e3bcbf80826a6bc64dd2158d5a2c2f7c75f";
    sha256 = "15d03snx1iv1r4r2zk8zcyq15gw4mq3w5dy1ja12z0gwrbhpyid7";
  };
}
