# DO NOT EDIT
# This file has been generated by
# $ /home/eon/vcs/nixpkgs-contrail/tools/sources.sh /home/eon/vcs/nixpkgs-contrail/tools/sources-R4.1.lst

{pkgs}:
{
  # Head of branch R4.1 of repository github.com/Juniper/contrail-build at 2019-03-29 10:24:19
  build = pkgs.fetchFromGitHub {
    name = "build";
    owner = "Juniper";
    repo = "contrail-build";
    rev = "b3e213e479619978b033b2006bb1be55e268e216";
    sha256 = "0cr3wc8s1yf2827nwmlc8jw4wdi4hw0nchq43rnpgpkmw04j9abh";
  };
  # Head of branch R4.1 of repository github.com/Juniper/contrail-controller at 2019-03-29 10:24:20
  controller = pkgs.fetchFromGitHub {
    name = "controller";
    owner = "Juniper";
    repo = "contrail-controller";
    rev = "4548916bed177b48f4629f8861138be0d26480b7";
    sha256 = "1084gvvmrziw2vqh4id61mgmmzhar9a51754g12c4c62arsvmqjy";
  };
  # Head of branch R4.1 of repository github.com/Juniper/contrail-generateds at 2019-03-29 10:24:48
  generateds = pkgs.fetchFromGitHub {
    name = "generateds";
    owner = "Juniper";
    repo = "contrail-generateds";
    rev = "1ea401a49f5eff118ece742282c290063de98ec2";
    sha256 = "1zxr29s82vgfmf9zw22p094vnxb5vfh1ahwn4vjgmjlsfmycm476";
  };
  # Head of branch R4.1 of repository github.com/Juniper/contrail-neutron-plugin at 2019-03-29 10:24:50
  neutronPlugin = pkgs.fetchFromGitHub {
    name = "neutronPlugin";
    owner = "Juniper";
    repo = "contrail-neutron-plugin";
    rev = "40ad78c635a28f24ef0fcf1a89f5817a59507ded";
    sha256 = "1f8hi1z860b95jcdjj2ylnn41sd76cz44v7bhjwh2nfmi09kqryf";
  };
  # Head of branch R4.1 of repository github.com/Juniper/contrail-sandesh at 2019-03-29 10:24:51
  sandesh = pkgs.fetchFromGitHub {
    name = "sandesh";
    owner = "Juniper";
    repo = "contrail-sandesh";
    rev = "ac8dfdcd26abbcd2886833331f6eebf37d35f04a";
    sha256 = "0j8frk5094sgvnivwhs5zx1vv96vir66sz17am70r3gq5h7hmjvv";
  };
  # Head of branch R4.1 of repository github.com/Juniper/contrail-third-party at 2019-03-29 10:24:53
  thirdParty = pkgs.fetchFromGitHub {
    name = "thirdParty";
    owner = "Juniper";
    repo = "contrail-third-party";
    rev = "ddc576e9c037e1ccc0e297a64ce92e4bedf95d63";
    sha256 = "07vq2gcqj3l450jj8fvz5zzslj8dxqpiyb3fs4ncqb2ayjaqxzlc";
  };
  # Head of branch R4.1 of repository github.com/Juniper/contrail-vrouter at 2019-03-29 10:24:54
  vrouter = pkgs.fetchFromGitHub {
    name = "vrouter";
    owner = "Juniper";
    repo = "contrail-vrouter";
    rev = "65e3ecf65f8859b03506bc842c119f59dbb8b456";
    sha256 = "0c5cal89j3s7xi5df86pqcvzzb41l02rlhavfjm8cf14qpmvnfkd";
  };
}
