# DO NOT EDIT
# This file has been generated by
# $ /home/eon/vcs/nixpkgs-contrail/tools/sources.sh /home/eon/vcs/nixpkgs-contrail/tools/sources-R3.2.lst

{pkgs}:
{
  # Head of branch R3.2 of repository github.com/Juniper/contrail-build at 2019-03-29 10:24:19
  build = pkgs.fetchFromGitHub {
    name = "build";
    owner = "Juniper";
    repo = "contrail-build";
    rev = "a18e25f1fca9c2c75b02faa26189f74b87b9e61f";
    sha256 = "126m7fbrrjxqkaq0wsjdlyllbxl989qrck10i3r3x638g57g4k6c";
  };
  # Head of branch R3.2 of repository github.com/Juniper/contrail-controller at 2019-03-29 10:24:20
  controller = pkgs.fetchFromGitHub {
    name = "controller";
    owner = "Juniper";
    repo = "contrail-controller";
    rev = "4b68fb57dc591f31996138d103671eaa6e819175";
    sha256 = "0412sm2qlqhl9c5rdkczn4kfgcskp4zy6ic4jxgnw6jbz1rid0lr";
  };
  # Head of branch R3.2 of repository github.com/Juniper/contrail-generateds at 2019-03-29 10:24:46
  generateds = pkgs.fetchFromGitHub {
    name = "generateds";
    owner = "Juniper";
    repo = "contrail-generateds";
    rev = "693687c1a16aa5d9c1a14f88f0b8ef29d3c1edd0";
    sha256 = "15nx0ws0zbsrcbzkqz4wmmnf92qwp2zvm4lhqz1852yfr0pav2ya";
  };
  # Head of branch R3.2 of repository github.com/Juniper/contrail-neutron-plugin at 2019-03-29 10:24:48
  neutronPlugin = pkgs.fetchFromGitHub {
    name = "neutronPlugin";
    owner = "Juniper";
    repo = "contrail-neutron-plugin";
    rev = "a29c077f684a8f07a91ac6b4ca08b373074c9228";
    sha256 = "1h4m11y5039z1xw905xnpd2xpmgmkay8zl36v22imw62w5h2ri7n";
  };
  # Head of branch R3.2 of repository github.com/Juniper/contrail-sandesh at 2019-03-29 10:24:50
  sandesh = pkgs.fetchFromGitHub {
    name = "sandesh";
    owner = "Juniper";
    repo = "contrail-sandesh";
    rev = "8cf1b46d2445716ebcabdc38fa180ccd89c172a4";
    sha256 = "1ypg01pia3qsyvj6icxvqm8rfi1irzyn639kfza00sghpjf87m5c";
  };
  # Head of branch R3.2 of repository github.com/Juniper/contrail-third-party at 2019-03-29 10:24:51
  thirdParty = pkgs.fetchFromGitHub {
    name = "thirdParty";
    owner = "Juniper";
    repo = "contrail-third-party";
    rev = "43fba6a6f4e3e62705593669dd96fa3803336517";
    sha256 = "1z2jkdjclm4hyn8vnjqpcqad9mm6vrlx0pyiy1dlwkxijg2lk7ci";
  };
  # Head of branch R3.2 of repository github.com/Juniper/contrail-vrouter at 2019-03-29 10:24:53
  vrouter = pkgs.fetchFromGitHub {
    name = "vrouter";
    owner = "Juniper";
    repo = "contrail-vrouter";
    rev = "5281e9e1857dca55ecff5a2e320d7079582649b8";
    sha256 = "1ya44214c42agkrrj8z25g9p74wwcqslcb3y3dn55zlpc0rpmz67";
  };
}
