# DO NOT EDIT
# This file has been generated by
# $ ./tools/sources.sh ./tools/sources-R5.0.lst

{pkgs}:
{
  # Head of branch R5.0 of repository github.com/Juniper/contrail-build at 2019-02-08 17:19:48
  build = pkgs.fetchFromGitHub {
    name = "build";
    owner = "Juniper";
    repo = "contrail-build";
    rev = "ae7a389b70b18ffdc29c559c0b23f6a9e1c3f8f3";
    sha256 = "0gv6zi630vw3s56ix0n99v6i4ag1r9djcs6g3rkaxfnl3s46mh6k";
  };
  # Head of branch R5.0 of repository github.com/Juniper/contrail-controller at 2019-02-08 17:19:49
  controller = pkgs.fetchFromGitHub {
    name = "controller";
    owner = "Juniper";
    repo = "contrail-controller";
    rev = "8ef7421d85f018386d1fb329368f4625d9ca1929";
    sha256 = "0zaq0c0dl6pg66bqnmnmarbvx8aapxlnq7n4gk0q1amx98xckdbd";
  };
  # Head of branch R5.0 of repository github.com/Juniper/contrail-neutron-plugin at 2019-02-08 17:19:55
  neutronPlugin = pkgs.fetchFromGitHub {
    name = "neutronPlugin";
    owner = "Juniper";
    repo = "contrail-neutron-plugin";
    rev = "7a6086975df0ded5b315c4ed89d010c4ec49b528";
    sha256 = "1pc2xmvifgfdjy1q52rj1p67yvszx52jaigb5r019y0llsmi0ghm";
  };
  # Head of branch R5.0 of repository github.com/Juniper/contrail-sandesh at 2019-02-08 17:19:56
  sandesh = pkgs.fetchFromGitHub {
    name = "sandesh";
    owner = "Juniper";
    repo = "contrail-sandesh";
    rev = "cd779c577b814882ae688a5a9c0854cfaa851f27";
    sha256 = "0qwd6ad1xb0rysz03jxzvrakkzs4lpkk7qljp1wykh3i3w4vk811";
  };
  # Head of branch R5.0 of repository github.com/Juniper/contrail-third-party at 2019-02-08 17:20:03
  thirdParty = pkgs.fetchFromGitHub {
    name = "thirdParty";
    owner = "Juniper";
    repo = "contrail-third-party";
    rev = "92489e37bb67d48fe8eaa07b1d689672e144e0db";
    sha256 = "0z8bx1hbxflzx65c8lvgvn0kjyr9h9fqfbzc7abnyfvygc5kp5mh";
  };
  # Head of branch R5.0 of repository github.com/Juniper/contrail-vrouter at 2019-02-08 17:20:04
  vrouter = pkgs.fetchFromGitHub {
    name = "vrouter";
    owner = "Juniper";
    repo = "contrail-vrouter";
    rev = "8d6385462b0ee4385934625667f8b21a7ebf85b9";
    sha256 = "1nlv0kl6ya8h4wp11glj68aa8vxwakm1zzmfwff5s0zpk9f739y4";
  };
  # Head of branch R5.0 of repository github.com/Juniper/contrail-common at 2019-02-08 17:20:13
  common = pkgs.fetchFromGitHub {
    name = "common";
    owner = "Juniper";
    repo = "contrail-common";
    rev = "452c7622d03e4dbb1de5c001615e983b4d370c0c";
    sha256 = "0zajgh26d8f3f272xk78rk7qcjdssmw7jag3ndw5imcakgxsyg56";
  };
  # Head of branch R5.0 of repository github.com/Juniper/contrail-analytics at 2019-02-08 17:20:15
  analytics = pkgs.fetchFromGitHub {
    name = "analytics";
    owner = "Juniper";
    repo = "contrail-analytics";
    rev = "a8b8959d128677051b584e538022c619d889c0dc";
    sha256 = "1jphccgbfv5nrpy6akwmvpzi1az1bpcr02k7h31817nyrz78agjl";
  };
  # Head of branch R5.0 of repository github.com/Juniper/contrail-api-client at 2019-02-08 17:20:25
  apiClient = pkgs.fetchFromGitHub {
    name = "apiClient";
    owner = "Juniper";
    repo = "contrail-api-client";
    rev = "a3e3462a6207239e23221b214c353a20b415da2e";
    sha256 = "10fqmkh11psqgwypbh37i5vsrxy87x05xpcg37kybfxzgbvlgnyd";
  };
}
