# This file was generated by https://github.com/kamilchm/go2nix v2.0-dev
[
  {
    goPackagePath = "github.com/gosuri/uitable";
    fetch = {
      type = "git";
      url = "https://github.com/gosuri/uitable";
      rev = "36ee7e946282a3fb1cfecd476ddc9b35d8847e42";
      sha256 = "1ff68fv9g1df91fwbrcq83ar429gb4fi2vsd22zjmhvmbqx2zkil";
    };
  }
  {
    goPackagePath = "github.com/jbowtie/gokogiri";
    fetch = {
      type = "git";
      url = "https://github.com/jbowtie/gokogiri";
      rev = "40b48594ca1866cf5d28177629b42f8a387377de";
      sha256 = "068a55dyscg20yvd8fyhcp1i4a8l4hdlp5xi9g1bbxylx5j4s5zx";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-runewidth";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-runewidth";
      rev = "9e777a8366cce605130a531d2cd6363d07ad7317";
      sha256 = "0vkrfrz3fzn5n6ix4k8s0cg0b448459sldq8bp4riavsxm932jzb";
    };
  }
  {
    goPackagePath = "gopkg.in/urfave/cli.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/urfave/cli.v2";
      rev = "d3ae77c26ac8db90639677e4831a728d33c36111";
      sha256 = "0fcw39hkwq4dn7n2m4gc4p66hb8h6c2161ah15iy2g45iypzpfkb";
    };
  }
]
