# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/gosuri/uitable";
    fetch = {
      type = "git";
      url = "https://github.com/gosuri/uitable";
      rev = "36ee7e946282a3fb1cfecd476ddc9b35d8847e42";
      sha256 = "1ff68fv9g1df91fwbrcq83ar429gb4fi2vsd22zjmhvmbqx2zkil";
    };
  }
  {
    goPackagePath = "github.com/jbowtie/gokogiri";
    fetch = {
      type = "git";
      url = "https://github.com/jbowtie/gokogiri";
      rev = "40b48594ca1866cf5d28177629b42f8a387377de";
      sha256 = "068a55dyscg20yvd8fyhcp1i4a8l4hdlp5xi9g1bbxylx5j4s5zx";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-runewidth";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-runewidth";
      rev = "97311d9f7767e3d6f422ea06661bc2c7a19e8a5d";
      sha256 = "0dxlrzn570xl7gb11hjy1v4p3gw3r41yvqhrffgw95ha3q9p50cg";
    };
  }
  {
    goPackagePath = "gopkg.in/urfave/cli.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/urfave/cli.v2";
      rev = "b2bf3c5abeb90da407891aecd1df2c5a1f6170c1";
      sha256 = "1x90qcnjcicq1d933bd9mdyjkwd0h9hdxgva45z85gqr7lavs5h3";
    };
  }
]
