# This file was generated by https://github.com/kamilchm/go2nix v2.0-dev
[
  {
    goPackagePath = "github.com/Jeffail/gabs";
    fetch = {
      type = "git";
      url = "https://github.com/Jeffail/gabs";
      rev = "2a3aa15961d5fee6047b8151b67ac2f08ba2c48c";
      sha256 = "1fx6fyl5x037viwlj319f3gsq749an17q5l6n2zvf3ny5wq0iqxr";
    };
  }
  {
    goPackagePath = "github.com/davecgh/go-spew";
    fetch = {
      type = "git";
      url = "https://github.com/davecgh/go-spew";
      rev = "346938d642f2ec3594ed81d874461961cd0faa76";
      sha256 = "0d4jfmak5p6lb7n2r6yvf5p1zcw0l8j74kn55ghvr7zr7b7axm6c";
    };
  }
  {
    goPackagePath = "github.com/eonpatapon/gremlin";
    fetch = {
      type = "git";
      url = "https://github.com/eonpatapon/gremlin";
      rev = "58c104e51c274b82ea5a5bbfb9c279f0e48235d9";
      sha256 = "1v9zy4wcd9mkj01rvg1rycfaswbrk9qah29ab7pzwwwdggcvksa8";
    };
  }
  {
    goPackagePath = "github.com/gocql/gocql";
    fetch = {
      type = "git";
      url = "https://github.com/gocql/gocql";
      rev = "04cbe7af6ed6de7b3d98480fca10df7ea9814bb6";
      sha256 = "1j1lx75wv89d8cp531rkfwq738l3nrvbgmg9rall5qsa37xnakp8";
    };
  }
  {
    goPackagePath = "github.com/golang/snappy";
    fetch = {
      type = "git";
      url = "https://github.com/golang/snappy";
      rev = "553a641470496b2327abcac10b36396bd98e45c9";
      sha256 = "0kssxnih1l722hx9219c7javganjqkqhvl3i0hp0hif6xm6chvqk";
    };
  }
  {
    goPackagePath = "github.com/google/go-cmp";
    fetch = {
      type = "git";
      url = "https://github.com/google/go-cmp";
      rev = "8099a9787ce5dc5984ed879a3bda47dc730a8e97";
      sha256 = "1399s4dcs91qic66ph6q1lqawfpp28qg3rlavhqnvsa50np60jwv";
    };
  }
  {
    goPackagePath = "github.com/gorilla/websocket";
    fetch = {
      type = "git";
      url = "https://github.com/gorilla/websocket";
      rev = "ea4d1f681babbce9545c9c5f3d5194a789c89f5b";
      sha256 = "1bhgs2542qs49p1dafybqxfs2qc072xv41w5nswyrknwyjxxs2a1";
    };
  }
  {
    goPackagePath = "github.com/hailocab/go-hostpool";
    fetch = {
      type = "git";
      url = "https://github.com/hailocab/go-hostpool";
      rev = "e80d13ce29ede4452c43dea11e79b9bc8a15b478";
      sha256 = "05ld4wp3illkbgl043yf8jq9y1ld0zzvrcg8jdij129j50xgfxny";
    };
  }
  {
    goPackagePath = "github.com/jawher/mow.cli";
    fetch = {
      type = "git";
      url = "https://github.com/jawher/mow.cli";
      rev = "0e80ee9f63156ea1954dc2375c33a1c7e752c25c";
      sha256 = "12sbgnsvkq4q8scq2nscydgwhldaf7hkw0iwaqd8mkqhi7mvwwam";
    };
  }
  {
    goPackagePath = "github.com/kr/pretty";
    fetch = {
      type = "git";
      url = "https://github.com/kr/pretty";
      rev = "cfb55aafdaf3ec08f0db22699ab822c50091b1c4";
      sha256 = "0441yi9ah9892hxdslv2h35bkfr75g7ajma0q45lqks84pawrdkg";
    };
  }
  {
    goPackagePath = "github.com/kr/text";
    fetch = {
      type = "git";
      url = "https://github.com/kr/text";
      rev = "7cafcd837844e784b526369c9bce262804aebc60";
      sha256 = "0br693pf6vdr1sfvzdz6zxq7hjpdgci0il4wj0v636r8lyy21vsx";
    };
  }
  {
    goPackagePath = "github.com/maraino/go-mock";
    fetch = {
      type = "git";
      url = "https://github.com/maraino/go-mock";
      rev = "c0658195ada54274d527cb1b09ff1d31765509d6";
      sha256 = "1c11cxaqmbwrf106l8647l5jpijqc6w9y11q1839dw0sczp7hrmc";
    };
  }
  {
    goPackagePath = "github.com/op/go-logging";
    fetch = {
      type = "git";
      url = "https://github.com/op/go-logging";
      rev = "b2cb9fa56473e98db8caba80237377e83fe44db5";
      sha256 = "01a6lkpj5p82gplddh55az194s9y3014p4j8x4zc8yv886z9c8gn";
    };
  }
  {
    goPackagePath = "github.com/pmezard/go-difflib";
    fetch = {
      type = "git";
      url = "https://github.com/pmezard/go-difflib";
      rev = "792786c7400a136282c1664665ae0a8db921c6c2";
      sha256 = "0c1cn55m4rypmscgf0rrb88pn58j3ysvc2d0432dp3c6fqg6cnzw";
    };
  }
  {
    goPackagePath = "github.com/satori/go.uuid";
    fetch = {
      type = "git";
      url = "https://github.com/satori/go.uuid";
      rev = "36e9d2ebbde5e3f13ab2e25625fd453271d6522e";
      sha256 = "0nc0ggn0a6bcwdrwinnx3z6889x65c20a2dwja0n8can3xblxs35";
    };
  }
  {
    goPackagePath = "github.com/streadway/amqp";
    fetch = {
      type = "git";
      url = "https://github.com/streadway/amqp";
      rev = "fc7fda2371f5327ad39211e09482845b8734cc72";
      sha256 = "08qa6xf6bx8sjg1bksllnkyd9f5yfyn2mh2zj4m9dgzq5sxnijc9";
    };
  }
  {
    goPackagePath = "github.com/stretchr/testify";
    fetch = {
      type = "git";
      url = "https://github.com/stretchr/testify";
      rev = "12b6f73e6084dad08a7c6e575284b177ecafbc71";
      sha256 = "01f80s0q64pw5drfgqwwk1wfwwkvd2lhbs56lhhkff4ni83k73fd";
    };
  }
  {
    goPackagePath = "github.com/willfaught/gockle";
    fetch = {
      type = "git";
      url = "https://github.com/willfaught/gockle";
      rev = "4f254e1e0f0a12485963192ff605f61f1933e71f";
      sha256 = "0bv3h103ar0bsadrkp1g7cwj3jdsj76jmqhcki4lqcy3f72hpgr3";
    };
  }
  {
    goPackagePath = "gopkg.in/inf.v0";
    fetch = {
      type = "git";
      url = "https://gopkg.in/inf.v0";
      rev = "3887ee99ecf07df5b447e9b00d9c0b2adaa9f3e4";
      sha256 = "0rf3vwyb8aqnac9x9d6ax7z5526c45a16yjm2pvkijr6qgqz8b82";
    };
  }
]
