# This file was generated by https://github.com/kamilchm/go2nix v2.0-dev
[
  {
    goPackagePath = "github.com/Jeffail/gabs";
    fetch = {
      type = "git";
      url = "https://github.com/Jeffail/gabs";
      rev = "7a0fed31069aba77993a518cc2f37b28ee7aa883";
      sha256 = "1yd7z5g0g51z7zk42nz7x7jg47s4a9iz77cgq3215ivaiygn9v3d";
    };
  }
  {
    goPackagePath = "github.com/akutz/goof";
    fetch = {
      type = "git";
      url = "https://github.com/akutz/goof";
      rev = "2321ba37c3513692d6f799d91fa66f28d11c7d7a";
      sha256 = "1r3rf8j4q7348f94y3m48gvnkkjgyqsl0k75v4118p8l47q5z9s3";
    };
  }
  {
    goPackagePath = "github.com/akutz/gotil";
    fetch = {
      type = "git";
      url = "https://github.com/akutz/gotil";
      rev = "6fa2e80bd3ac40f15788cfc3d12ebba49a0add92";
      sha256 = "11490z6ajw56mv156rscylcfa3m10bmz5q6z4p59jjd6r4lffmzl";
    };
  }
  {
    goPackagePath = "github.com/davecgh/go-spew";
    fetch = {
      type = "git";
      url = "https://github.com/davecgh/go-spew";
      rev = "346938d642f2ec3594ed81d874461961cd0faa76";
      sha256 = "0d4jfmak5p6lb7n2r6yvf5p1zcw0l8j74kn55ghvr7zr7b7axm6c";
    };
  }
  {
    goPackagePath = "github.com/eonpatapon/gremlin";
    fetch = {
      type = "git";
      url = "https://github.com/eonpatapon/gremlin";
      rev = "15a2a60433e5e63f6cceb83f12288199bcf5cd12";
      sha256 = "0g6jcf945hv275azpxfg3w1248jw03facmvv4gdchg34rsl8gg5r";
    };
  }
  {
    goPackagePath = "github.com/gocql/gocql";
    fetch = {
      type = "git";
      url = "https://github.com/gocql/gocql";
      rev = "04cbe7af6ed6de7b3d98480fca10df7ea9814bb6";
      sha256 = "1j1lx75wv89d8cp531rkfwq738l3nrvbgmg9rall5qsa37xnakp8";
    };
  }
  {
    goPackagePath = "github.com/golang/snappy";
    fetch = {
      type = "git";
      url = "https://github.com/golang/snappy";
      rev = "2e65f85255dbc3072edf28d6b5b8efc472979f5a";
      sha256 = "05w6mpc4qcy0pv8a2bzng8nf4s5rf5phfang4jwy9rgf808q0nxf";
    };
  }
  {
    goPackagePath = "github.com/google/go-cmp";
    fetch = {
      type = "git";
      url = "https://github.com/google/go-cmp";
      rev = "8099a9787ce5dc5984ed879a3bda47dc730a8e97";
      sha256 = "1399s4dcs91qic66ph6q1lqawfpp28qg3rlavhqnvsa50np60jwv";
    };
  }
  {
    goPackagePath = "github.com/gorilla/websocket";
    fetch = {
      type = "git";
      url = "https://github.com/gorilla/websocket";
      rev = "ea4d1f681babbce9545c9c5f3d5194a789c89f5b";
      sha256 = "1bhgs2542qs49p1dafybqxfs2qc072xv41w5nswyrknwyjxxs2a1";
    };
  }
  {
    goPackagePath = "github.com/hailocab/go-hostpool";
    fetch = {
      type = "git";
      url = "https://github.com/hailocab/go-hostpool";
      rev = "e80d13ce29ede4452c43dea11e79b9bc8a15b478";
      sha256 = "05ld4wp3illkbgl043yf8jq9y1ld0zzvrcg8jdij129j50xgfxny";
    };
  }
  {
    goPackagePath = "github.com/jawher/mow.cli";
    fetch = {
      type = "git";
      url = "https://github.com/jawher/mow.cli";
      rev = "2f22195f169da29d54624afd9eb83ada5c9e4ee9";
      sha256 = "1k37b567n3q48w3nsxszypx1ndqynwa8xqa6jsm7075n6rdj0aii";
    };
  }
  {
    goPackagePath = "github.com/kardianos/osext";
    fetch = {
      type = "git";
      url = "https://github.com/kardianos/osext";
      rev = "ae77be60afb1dcacde03767a8c37337fad28ac14";
      sha256 = "056dkgxrqjj5r18bnc3knlpgdz5p3yvp12y4y978hnsfhwaqvbjz";
    };
  }
  {
    goPackagePath = "github.com/kr/pretty";
    fetch = {
      type = "git";
      url = "https://github.com/kr/pretty";
      rev = "73f6ac0b30a98e433b289500d779f50c1a6f0712";
      sha256 = "18m4pwg2abd0j9cn5v3k2ksk9ig4vlwxmlw9rrglanziv9l967qp";
    };
  }
  {
    goPackagePath = "github.com/kr/text";
    fetch = {
      type = "git";
      url = "https://github.com/kr/text";
      rev = "e2ffdb16a802fe2bb95e2e35ff34f0e53aeef34f";
      sha256 = "1gm5bsl01apvc84bw06hasawyqm4q84vx1pm32wr9jnd7a8vjgj1";
    };
  }
  {
    goPackagePath = "github.com/maraino/go-mock";
    fetch = {
      type = "git";
      url = "https://github.com/maraino/go-mock";
      rev = "4c74c434cd3a9e9a70ed1eeb56646a1d3fac372f";
      sha256 = "1kx6azpxjn098h8whdkq0c41ry5cqnyq3aif0r9w7yyaqvzxif87";
    };
  }
  {
    goPackagePath = "github.com/op/go-logging";
    fetch = {
      type = "git";
      url = "https://github.com/op/go-logging";
      rev = "b2cb9fa56473e98db8caba80237377e83fe44db5";
      sha256 = "01a6lkpj5p82gplddh55az194s9y3014p4j8x4zc8yv886z9c8gn";
    };
  }
  {
    goPackagePath = "github.com/pmezard/go-difflib";
    fetch = {
      type = "git";
      url = "https://github.com/pmezard/go-difflib";
      rev = "792786c7400a136282c1664665ae0a8db921c6c2";
      sha256 = "0c1cn55m4rypmscgf0rrb88pn58j3ysvc2d0432dp3c6fqg6cnzw";
    };
  }
  {
    goPackagePath = "github.com/satori/go.uuid";
    fetch = {
      type = "git";
      url = "https://github.com/satori/go.uuid";
      rev = "36e9d2ebbde5e3f13ab2e25625fd453271d6522e";
      sha256 = "0nc0ggn0a6bcwdrwinnx3z6889x65c20a2dwja0n8can3xblxs35";
    };
  }
  {
    goPackagePath = "github.com/streadway/amqp";
    fetch = {
      type = "git";
      url = "https://github.com/streadway/amqp";
      rev = "8e4aba63da9fc5571e01c6a45dc809a58cbc5a68";
      sha256 = "1940r74pzgc4q3a4cjdrzh6l42m6l39zkpkbvd9g1l5c9vsfma00";
    };
  }
  {
    goPackagePath = "github.com/stretchr/testify";
    fetch = {
      type = "git";
      url = "https://github.com/stretchr/testify";
      rev = "12b6f73e6084dad08a7c6e575284b177ecafbc71";
      sha256 = "01f80s0q64pw5drfgqwwk1wfwwkvd2lhbs56lhhkff4ni83k73fd";
    };
  }
  {
    goPackagePath = "github.com/willfaught/gockle";
    fetch = {
      type = "git";
      url = "https://github.com/willfaught/gockle";
      rev = "4f254e1e0f0a12485963192ff605f61f1933e71f";
      sha256 = "0bv3h103ar0bsadrkp1g7cwj3jdsj76jmqhcki4lqcy3f72hpgr3";
    };
  }
  {
    goPackagePath = "gopkg.in/inf.v0";
    fetch = {
      type = "git";
      url = "https://gopkg.in/inf.v0";
      rev = "d2d2541c53f18d2a059457998ce2876cc8e67cbf";
      sha256 = "00k5iqjcp371fllqxncv7jkf80hn1zww92zm78cclbcn4ybigkng";
    };
  }
]
