#!/usr/bin/env bash
#
# A script that creates a sources.nix skeleton by looking for the latest
# commit in the specified branch.
#
# Usage: sources.sh sources-master.lst
#
# The format of each line of the input file is
# Attribute Owner Repos Branch

echo "# DO NOT EDIT"
echo "# This file has been generated by"
echo "# $ $0 $@"
echo
echo "{pkgs}:"
echo "{"

while read -r ATTRIBUTE OWNER REPOS BRANCH; do
    tmpfile=$(mktemp)
    tmpdir=$(mktemp -d)
    echo "  # Head of branch $BRANCH of repository github.com/$OWNER/$REPOS at $(date +'%F %T')"
    COMMITID=$(curl --silent https://api.github.com/repos/$OWNER/$REPOS/branches/$BRANCH | jq -r '.commit.sha')
    curl --silent -L https://github.com/$OWNER/$REPOS/archive/$COMMITID.tar.gz > $tmpfile

    tar -C $tmpdir/ -xf $tmpfile
    SHA256=$(find $tmpdir/ -maxdepth 1 -mindepth 1 -exec nix-hash --type sha256 --base32 '{}' \;)

    rm -f $tmpfile
    rm -rf $tmpdir

    echo "  $ATTRIBUTE = pkgs.fetchFromGitHub {"
    echo "    name = \"$ATTRIBUTE\";";
    echo "    owner = \"$OWNER\";";
    echo "    repo = \"$REPOS\";"
    echo "    rev = \"$COMMITID\";"
    echo "    sha256 = \"$SHA256\";"
    echo "  };"
done < $1

echo "}"
